runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\.(html|css|js|json|png|jpg|jpeg|svg|ico|txt))
    static_files: build/\1
    upload: build/(.*\.(html|css|js|json|png|jpg|jpeg|svg|ico|txt))
    secure: always
    redirect_http_response_code: 301

  # backend
  - url: /.*
    script: auto
